###  This notebook require Numpy version 1.10 or greater and Pandas version 0.18 or greater

In [1]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

In [13]:
np.__version__

'1.10.4'

In [14]:
pd.__version__

u'0.18.0'

In [2]:
df1=DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df2 = DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [3]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [4]:
#example of a many-to-one merge situation
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [5]:
#Note that I didn’t specify which column to join on. If not specified, merge uses the
#overlapping column names as the keys
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [6]:
#If the column names are different
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df3

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [7]:
df4 = DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})
df4

data2 rkey
0      0    a
1      1    b
2      2    d

In [14]:
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [17]:
pd.merge(df1,df2,how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [18]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
df2 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],'data2': range(5)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [19]:
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [20]:
pd.merge(df1, df2, on='key', how='left') #Many-to-many merges
#Many-to-many joins form the Cartesian product of the rows

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [21]:
pd.merge(df1, df2, how='inner')

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [22]:
#To merge with multiple keys, pass a list of column names:
left = DataFrame({'key1': ['foo', 'foo', 'bar'],'key2': ['one', 'two', 'one'],'lval': [1, 2, 3]})
right = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],'key2': ['one', 'one', 'one', 'two'],'rval': [4, 5, 6, 7]})
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [24]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [25]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [23]:
#merge has a suffixes option for specifying strings to append to overlapping names in the left and right DataFrame objects
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [26]:
#Merging on Index
#you can pass left_index=True or right_index=True (or both) to indicate that the index should be used as the merge key:
left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [27]:
right1

group_val
a        3.5
b        7.0

In [28]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [29]:
pd.merge(left1, right1, left_on='key',how='outer', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

###  
DataFrame has a more convenient join instance for merging by index. It can also be
used to combine together many DataFrame objects having the same or similar indexes
but non-overlapping columns

In [30]:
''''''
left1.join(right1,how='outer')

key  value  group_val
0    a    0.0        NaN
1    b    1.0        NaN
2    a    2.0        NaN
3    a    3.0        NaN
4    b    4.0        NaN
5    c    5.0        NaN
a  NaN    NaN        3.5
b  NaN    NaN        7.0

In [31]:
left1.join(right1,how='outer',on='key')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [32]:
#Concatenating Along an Axis
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [34]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [35]:
pd.concat([s1, s2, s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [36]:
s4 = pd.concat([s1 * 5, s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [37]:
pd.concat([s1, s4], axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [38]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

In [40]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'g', 'b', 'e']])

0    1
a  0.0  0.0
g  NaN  6.0
b  1.0  5.0
e  NaN  NaN

In [41]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [42]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [43]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [44]:
df1 = DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],columns=['one', 'two'])
df2 = DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],columns=['three', 'four'])
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [45]:
pd.concat({'level1': df1, 'level2': df2}, axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [46]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'],names=['upper', 'lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [47]:
df1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
df1

a         b         c         d
0 -1.689363  2.271494 -0.756045  3.133023
1  1.607826 -0.861958 -0.816524  0.976887
2 -0.609630  0.888465  0.481721  0.018858

In [48]:
df2

b         d         a
0  1.532828  0.188005  1.036899
1 -0.820820  1.403111  0.747335

In [49]:
pd.concat([df1, df2], ignore_index=True)

a         b         c         d
0 -1.689363  2.271494 -0.756045  3.133023
1  1.607826 -0.861958 -0.816524  0.976887
2 -0.609630  0.888465  0.481721  0.018858
3  1.036899  1.532828       NaN  0.188005
4  0.747335 -0.820820       NaN  1.403111

In [50]:
pd.concat([df1, df2])

a         b         c         d
0 -1.689363  2.271494 -0.756045  3.133023
1  1.607826 -0.861958 -0.816524  0.976887
2 -0.609630  0.888465  0.481721  0.018858
0  1.036899  1.532828       NaN  0.188005
1  0.747335 -0.820820       NaN  1.403111

## Combining Data with Overlap 

In [51]:

a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],index=['f', 'e', 'd', 'c', 'b', 'a'])
b = Series(np.arange(len(a), dtype=np.float64),index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [52]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [53]:
np.where(pd.isnull(a), b, a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

### Series has a combine_first method, which performs the equivalent of this operation plus data alignment

In [54]:

b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [55]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [56]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [57]:
df1 = DataFrame({'a': [1., np.nan, 5., np.nan],'b': [np.nan, 2., np.nan, 6.],'c': range(2, 18, 4)})
df2 = DataFrame({'a': [5., 4., np.nan, 3., 7.],'b': [np.nan, 3., 4., 6., 8.]})
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [58]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [59]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

### Reshaping and Pivoting 

In [60]:
#
data = DataFrame(np.arange(6).reshape((2, 3)),index=pd.Index(['Ohio', 'Colorado'], name='state'),
                 columns=pd.Index(['one', 'two', 'three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [61]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [62]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [63]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [64]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

### Unstacking might introduce missing data if all of the values in the level aren’t found in each of the subgroups 

In [65]:
s1 = Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [66]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [67]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [68]:
df = DataFrame({'left': result, 'right': result + 5},columns=pd.Index(['left', 'right'], name='side'))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [69]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [70]:
df.unstack('state').stack('side')

state         Ohio  Colorado
number side                 
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

In [71]:
#Removing Duplicates
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,'k2': [1, 1, 2, 3, 3, 4, 4]})

In [72]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [73]:
data.duplicated() #row is a duplicate or not:

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [74]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [75]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [76]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [77]:
data.drop_duplicates(['v1'])

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [78]:
'''duplicated and drop_duplicates by default keep the first observed value combination.
Passing take_last=True will return the last one'''
data.drop_duplicates(['k1', 'k2'], take_last=True)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: the take_last=True keyword is deprecated, use keep='last' instead
  app.launch_new_instance()


k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

In [80]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

## Transforming Data Using a Function or Mapping 

In [81]:
data=DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [82]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}
meat_to_animal

{'bacon': 'pig',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastrami': 'cow',
 'pulled pork': 'pig'}

In [83]:
#Suppose you wanted to add a column indicating the type of animal that each food came from.
data['animal']=data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [84]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [85]:
#Replacing Values
data = Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [86]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [87]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [88]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [89]:
#Renaming Axis Indexes
data = DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [90]:
data.index.map(str.upper)

array(['OHIO', 'COLORADO', 'NEW YORK'], dtype=object)

In [91]:
data.index = data.index.map(str.upper)

In [92]:
data #now "OHIO" is capital

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [93]:
data.index

Index([u'OHIO', u'COLORADO', u'NEW YORK'], dtype='object')

In [94]:
data.rename(index=str.title, columns=str.upper)
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [95]:
data.rename(index={'OHIO': 'INDIANA'},columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [96]:
#Discretization and Binning
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [97]:
bins = [18, 25, 35, 60, 100]

In [98]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [99]:
cats.labels

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  if __name__ == '__main__':


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [100]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [101]:
cats.levels

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
  if __name__ == '__main__':


Index([u'(18, 25]', u'(25, 35]', u'(35, 60]', u'(60, 100]'], dtype='object')

In [102]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [103]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, object): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [104]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [105]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.53, 0.73], (0.73, 0.93], (0.73, 0.93], (0.73, 0.93], (0.12, 0.32], ..., (0.12, 0.32], (0.53, 0.73], (0.12, 0.32], (0.12, 0.32], (0.32, 0.53]]
Length: 20
Categories (4, object): [(0.12, 0.32] < (0.32, 0.53] < (0.53, 0.73] < (0.73, 0.93]]

In [106]:
data

array([ 0.59043182,  0.88890532,  0.73883536,  0.82682093,  0.29806258,
        0.64688705,  0.93027971,  0.39831115,  0.12091443,  0.22320796,
        0.53345477,  0.42876499,  0.29655695,  0.21452387,  0.43974203,
        0.32145226,  0.56471491,  0.1412621 ,  0.23868667,  0.33804413])

In [107]:
np.sort(data)

array([ 0.12091443,  0.1412621 ,  0.21452387,  0.22320796,  0.23868667,
        0.29655695,  0.29806258,  0.32145226,  0.33804413,  0.39831115,
        0.42876499,  0.43974203,  0.53345477,  0.56471491,  0.59043182,
        0.64688705,  0.73883536,  0.82682093,  0.88890532,  0.93027971])

In [108]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles
cats

[(-0.664, -0.00843], (-0.00843, 0.654], (-0.00843, 0.654], [-3.0233, -0.664], [-3.0233, -0.664], ..., (0.654, 3.134], (-0.00843, 0.654], (-0.664, -0.00843], [-3.0233, -0.664], (-0.00843, 0.654]]
Length: 1000
Categories (4, object): [[-3.0233, -0.664] < (-0.664, -0.00843] < (-0.00843, 0.654] < (0.654, 3.134]]

In [109]:
pd.value_counts(cats)

(0.654, 3.134]        250
(-0.00843, 0.654]     250
(-0.664, -0.00843]    250
[-3.0233, -0.664]     250
dtype: int64

In [111]:
cats=pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])
cats
#Similar to cut you can pass your own quantiles (numbers between 0 and 1, inclusive)

[(-1.298, -0.00843], (-0.00843, 1.252], (-0.00843, 1.252], (-1.298, -0.00843], (-1.298, -0.00843], ..., (-0.00843, 1.252], (-0.00843, 1.252], (-1.298, -0.00843], (-1.298, -0.00843], (-0.00843, 1.252]]
Length: 1000
Categories (4, object): [[-3.0233, -1.298] < (-1.298, -0.00843] < (-0.00843, 1.252] < (1.252, 3.134]]

In [112]:
pd.value_counts(cats)

(-0.00843, 1.252]     400
(-1.298, -0.00843]    400
(1.252, 3.134]        100
[-3.0233, -1.298]     100
dtype: int64

In [113]:
#Detecting and Filtering Outliers
np.random.seed(12345)

In [114]:
data = DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [115]:
col = data[3]

In [116]:
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [117]:
data[3][np.abs(data[3])>3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [118]:
data[(np.abs(data) > 3).any(1)]#To select all rows having a value exceeding 3 or -3,

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [120]:
#Here is code to cap values outside the interval -3 to 3:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()
#The ufunc np.sign returns an array of 1 and -1 depending on the sign of the values.

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [2]:
#Permutation and Random Sampling
df = DataFrame(np.arange(5 * 4).reshape(5, 4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [3]:
sampler = np.random.permutation(5)
sampler

array([4, 0, 3, 2, 1])

In [4]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7

In [5]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11

## Computing Indicator/Dummy Variables
Another type of transformation for statistical modeling or machine learning applications is converting a categorical variable into a “dummy” or “indicator” matrix.
If a column in a DataFrame has k distinct values, you would derive a matrix or DataFrame containing k columns containing all 1’s and 0’s. pandas has a get_dummies function for doing this.

In [8]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(2,8)})
pd.get_dummies(df['key'])

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [9]:
df

data1 key
0      2   b
1      3   b
2      4   a
3      5   c
4      6   a
5      7   b

In [10]:
values = np.random.rand(10)
values

array([ 0.94922258,  0.45067833,  0.80667271,  0.08174986,  0.85440959,
        0.51256441,  0.1684774 ,  0.60371435,  0.34064919,  0.93944306])

In [11]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1]
0       0.0         0.0         0.0         0.0       1.0
1       0.0         0.0         1.0         0.0       0.0
2       0.0         0.0         0.0         0.0       1.0
3       1.0         0.0         0.0         0.0       0.0
4       0.0         0.0         0.0         0.0       1.0
5       0.0         0.0         1.0         0.0       0.0
6       1.0         0.0         0.0         0.0       0.0
7       0.0         0.0         0.0         1.0       0.0
8       0.0         1.0         0.0         0.0       0.0
9       0.0         0.0         0.0         0.0       1.0

In [12]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [13]:
#split is often combined with strip to trim whitespace (including newlines):
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [14]:
first, second, third = pieces

In [15]:
first

'a'

In [16]:
first + '::' + second + '::' + third

'a::b::guido'

In [17]:
'::'.join(pieces)

'a::b::guido'

In [18]:
type(pieces)

list

In [19]:
val.index(',')

1

In [21]:
val.find(':')

-1

In [22]:
val.count(',')

2

In [23]:
val.replace(',', '::')

'a::b:: guido'

In [24]:
val.replace(',', '')

'ab guido'

In [25]:
import re
text = "foo bar\t baz \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']